"use client";
import { useState, useEffect, useRef } from "react";
import { supabase } from "@/lib/supabaseClient";
import { useReactToPrint } from "react-to-print";
import { Printer, ArrowLeft, Download, Share2 } from "lucide-react";
import Link from "next/link";
import { useParams } from "next/navigation";

export default function ExamViewPage() {
  const { id } = useParams();
  const printRef = useRef<HTMLDivElement>(null);
  const [exam, setExam] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchExam = async () => {
        const { data } = await supabase.from('exam_papers').select('*').eq('id', id).single();
        if (data) setExam(data);
        setLoading(false);
    };
    fetchExam();
  }, [id]);

  const handlePrint = useReactToPrint({
    contentRef: printRef,
    documentTitle: exam?.title || "Exam Paper",
  });

  if (loading) return <div className="p-10 text-center">Loading Paper...</div>;
  if (!exam) return <div className="p-10 text-center">Exam not found.</div>;

  return (
    <div className="min-h-screen bg-slate-100 flex flex-col">
       {/* Actions Header */}
       <div className="bg-white border-b border-slate-200 px-6 py-4 flex justify-between items-center shadow-sm sticky top-0 z-10 print:hidden">
           <div className="flex items-center gap-4">
               <Link href="/tutor/dashboard/my-exams" className="p-2 hover:bg-slate-100 rounded-full transition-colors"><ArrowLeft className="w-5 h-5 text-slate-600"/></Link>
               <div>
                   <h1 className="font-bold text-slate-800 text-lg">{exam.title}</h1>
                   <p className="text-xs text-slate-500">Saved on {new Date(exam.created_at).toLocaleDateString()}</p>
               </div>
           </div>
           <div className="flex gap-3">
               <button onClick={() => handlePrint()} className="flex items-center gap-2 bg-indigo-600 text-white px-6 py-2.5 rounded-xl font-bold text-sm hover:bg-indigo-700 shadow-lg transition-all">
                   <Printer className="w-4 h-4"/> Print / Download PDF
               </button>
           </div>
       </div>

       {/* Paper Preview (Read Only) */}
       <div className="flex-1 overflow-y-auto p-8 flex justify-center">
           <div ref={printRef} className="bg-white shadow-2xl min-h-[297mm] w-[210mm] p-[20mm] relative print:shadow-none print:w-full print:h-auto print:p-0 print:m-0">
               {/* Header */}
               <div className="text-center border-b-2 border-black pb-6 mb-8">
                   <h1 className="text-4xl font-black mb-2">{exam.institute_name}</h1>
                   <h2 className="text-xl font-bold mb-4">{exam.title}</h2>
                   <div className="flex justify-between font-bold text-sm uppercase border-t-2 border-slate-100 pt-4">
                        <span>Time: {exam.duration}</span>
                        <span>Marks: {exam.total_marks}</span>
                   </div>
               </div>

               {/* Instructions */}
               {exam.settings?.instructions && (
                   <div className="mb-8 text-sm text-slate-800 leading-relaxed" dangerouslySetInnerHTML={{__html: exam.settings.instructions}}></div>
               )}

               {/* Questions */}
               <div className="space-y-8">
                   {exam.questions.map((q: any, idx: number) => (
                       <div key={idx} className="flex gap-3 items-start break-inside-avoid">
                           <span className="font-bold text-lg w-6">{idx + 1}.</span>
                           <div className="flex-1">
                               <div className="font-medium text-slate-900 mb-2 [&_p]:inline" dangerouslySetInnerHTML={{__html: q.question_text}}></div>
                               {q.question_type === 'mcq' && q.options && (
                                   <div className="grid grid-cols-2 gap-x-8 gap-y-2 mt-2">
                                       {q.options.map((opt: any, i: number) => (
                                           <div key={i} className="flex gap-2 text-sm items-start">
                                               <span className="font-bold">({String.fromCharCode(97 + i)})</span>
                                               <span>{opt.option_text}</span>
                                           </div>
                                       ))}
                                   </div>
                               )}
                           </div>
                           <div className="font-bold text-sm min-w-[2rem] text-right">[{q.marks}]</div>
                       </div>
                   ))}
               </div>

               {/* Watermark */}
               {exam.settings?.showWatermark && (
                   <div className="mt-12 pt-4 border-t border-slate-200 text-center text-xs text-slate-400 font-medium">
                       Generated by NextPrep Question Builder
                   </div>
               )}
           </div>
       </div>
    </div>
  );
}